kind: TrexConfig
metadata:
  name: trex-instance
  image: trex-container-image
spec:
  mgmtIP: 192.168.1.100
  mgmtGateway: 192.168.1.1
  networkType: VF
  port:
    - ifName: ens2f0v0
      ip: 10.0.0.2/24
      gateway: 10.0.0.1
      vlan: 100
    - ifName: ens2f0v1
      ip: 10.0.1.2/24
      gateway: 10.0.1.1
      vlan: 101